
SECRET_KEY = os.getenv("SECRET_KEY")
ALLOWED_SECRET_KEYS = os.getenv("ALLOWED_SECRET_KEYS") # Se cargará como string
USER_SYSTEM_BALANCE = os.getenv("USER_SYSTEM_BALANCE")
PASSWORD_SYSTEM_BALANCE = os.getenv("PASSWORD_SYSTEM_BALANCE")